[workspace]
resolver = "2"
members = [
    "mcts-traits",
    "mcts-engine",
    "mcts-envs",
    "environments/connect4",
    "environments/blokus",
    "environments/tzf8",
    "environments/hex",
    "environments/sequence",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Pankaj <pan1997>"]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
mcts-traits = { path = "mcts-traits" }
mcts-engine = { path = "mcts-engine" }
mcts-envs = { path = "mcts-envs" }
connect4 = { path = "environments/connect4" }
blokus = { path = "environments/blokus" }
tzf8 = { path = "environments/tzf8" }
hex = { path = "environments/hex" }
sequence = { path = "environments/sequence" }
rand = "0.8"
rand_distr = "0.4"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"