[workspace]

[workspace.package]
version = "0.1.0"
edition = "2021"


[workspace.dependencies]
rand = "*"

[package]
name = "ai"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib = {path = "lib/"}
mcts = {path = "mcts/"}