[workspace]
members = [
  "examples",
  "lib",
  "mcts",
  "blokus",
  "connect4", 
  "connect6",
  "othello",
  "tzf8",
  "ttt",
  "hex",
  "chess_"
]

[workspace.package]
version = "0.1.0"
edition = "2021"


[workspace.dependencies]
rand = "*"
graphviz-rust = "*"
num = "*"