[workspace]
resolver = "2"
members = [
    "mcts-traits",
    "mcts-engine",
    "mcts-envs",
    "connect4",
    "blokus",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Pankaj <pan1997>"]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
mcts-traits = { path = "mcts-traits" }
mcts-engine = { path = "mcts-engine" }
mcts-envs = { path = "mcts-envs" }
connect4 = { path = "connect4" }
blokus = { path = "blokus" }
rand = "0.8"
rand_distr = "0.4"